sonar.organization=dolmen-go
sonar.projectKey=dolmen-go_openapi-preprocessor

sonar.go.activate=true
sonar.dre.go.activate=true

# Output of "go test -json"
# sonar.go.tests.reportPaths=

# https://docs.sonarsource.com/sonarqube-server/analyzing-source-code/test-coverage/go-test-coverage
sonar.go.coverage.reportPaths=coverage.out

# sonar.go.golangci-lint.reportPaths=

# TODO
# sonar.githubactions.actionlint.reportPaths

# https://sonarcloud.io/project/settings?category=exclusions&id=dolmen-go_openapi-preprocessor

# Ignore duplications in unit test code
sonar.cpd.exclusions=**/*_test.go

# Ignore coverage report for _test.go because "go test" doesn't report them anyway
sonar.coverage.exclusions=**/*_test.go


# Get token: https://sonarcloud.io/project/configuration/GitHubManual?id=dolmen-go_openapi-preprocessor
# List issues:
#  SONAR_TOKEN= curl --variable %SONAR_TOKEN --expand-user '{{SONAR_TOKEN}}:' 'https://sonarcloud.io/api/issues/search?componentKeys=dolmen-go_openapi-preprocessor&resolved=false'
#
# curl --variable '%SONAR_TOKEN' --expand-user '{{SONAR_TOKEN}}:' 'https://sonarcloud.io/api/issues/search?componentKeys=dolmen-go_openapi-preprocessor&resolved=false' | jq .
